---
title: "Análisis Exploratorio Datos"
output: html_document
---

Librerías:

```{r}
library(tidyverse)
```


# Análisis Exploratorio de los Datos

```{r}
data <- read.csv("C:/Users/ruben/OneDrive/Escritorio/UPNA/CIENCIA DE DATOS/6ºSemestre/AnalisisMultivarianteVisualizacionDatos/Trabajo Final/Motor_Vehicle_Collisions_-_Crashes.csv")
View(data)
```


## Contribuiting Factor Vehicle:


## Vehicle Type Code:

```{r}
dataVT <- data |> 
  dplyr::select(VEHICLE.TYPE.CODE.1, VEHICLE.TYPE.CODE.2, VEHICLE.TYPE.CODE.3, VEHICLE.TYPE.CODE.4, VEHICLE.TYPE.CODE.5)

missing_data <- dataVT %>%
  summarise(across(everything(), ~ sum(is.na(.) | (is.numeric(.) & is.nan(.)) | .=="")))

missing_data_long <- missing_data %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "Missing_Count")


# Crear el gráfico de barras
ggplot(missing_data_long, aes(x = Variable, y = Missing_Count, fill = Variable)) +
  geom_col() +  # Gráfico de barras
  labs(
    x = "Variable",  # Etiqueta del eje X
    y = "Número de valores problemáticos",  # Etiqueta del eje Y
    title = "Valores faltantes, no numéricos o cadenas vacías por variable"  # Título
  ) +
  theme_minimal() +  # Tema minimalista
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotar etiquetas del eje X
```








